### ISSUE TITLE
undefined API Key is sent with request as a header 'Authorization  : undefined'

### ISSUE THREAD

**Issue by theredpea** [inversoft/passport-javascript-client#2]
Sending requests with header 'Authorization  : undefined'
will cause a 401, even if omitting the header may result in 200;;

Consider ; dont add to the header object if the value is falsey;
           ```
       header: function (key, value) {
                        if (value){
                              this.headers[key] = value;
                        }
                        return this;
                  },
```

Or, dont send the header if the value is falsey
```

                        xhr.open(this.method, this.restUrl, true);
                        for (var header in this.headers) {
                              if (this.headers[header]) {
                                    xhr.setRequestHeader(header, this.headers[header]);
                              }
                        }
                        xhr.send(this.body);
```

**Comment by robotdan** [comment]
Thanks @theredpea, I've added some additional code to be more defensive about adding header values with null or undefined values. 

Fixed under 6f9a648305d9762943bf22c04d796004ad73afe0. 

Thanks for helping to improve this library.
